services:
  chromium:
    shm_size: "2g"
    image: seleniarm/standalone-chromium:113.0
    ports:
      - 4444:4444
      - 7900:7900
      - 5900:5900
    networks:
      - wp-bot-eonus
    volumes:
      - type: volume
        source: seldata
        target: /home/seluser
    environment:
      - SE_SCREEN_WIDTH=500
      - SE_SCREEN_HEIGHT=500
      - SE_START_NO_VNC=false
      - SE_START_VNC=false
      - SE_NODE_MAX_SESSIONS=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  app:
    build:
      dockerfile: Dockerfile
    command: ["python3", "main.py"]
    networks:
      - wp-bot-eonus
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - /Users/enes/Desktop/WhatsappBot:/app
    environment:
      - IP_ADDR=chromium
    depends_on:
      chromium:
        condition: service_healthy
volumes:
  seldata:

networks:
  wp-bot-eonus:
    name: wp-bot-eonus
